# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

executors:
  openjdk:
    parameters:
      jdk-version:
        type: enum
        enum: ["8", "11"]
    docker:
      - image: circleci/clojure:openjdk-<< parameters.jdk-version>>-tools-deps-1.10.0.442-node-browsers
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
      CLOJURE_VERSION: "1.10.1.462"
    working_directory: ~/repo

commands:
  build:
    description: "Checkout, build and test"
    steps:
      - checkout

      - run:
          name: Update linux packages
          command: |
            sudo apt-get update
            # packages needed for planck
            sudo apt-get install -y javascriptcoregtk-4.0 libglib2.0-dev libzip-dev libcurl4-gnutls-dev

      - run:
          name: Install planck
          command: |
            curl -O https://planck-repl.org/releases/2.24.0-debian-9.0-x86_64/planck
            chmod +x planck
            echo e19e28efb00733912c8cf114e56da10b  planck | md5sum --check
            sudo mv planck /usr/local/bin
            planck --version

      - restore_cache:
          keys:
            - v1-npm-dependencies-{{ checksum "package-lock.json" }}
            - v1-npm-dependencies- # fallback if cache not found

      - run:
          name: Install karma command line
          command: sudo npm install karma-cli -g

      - run:
          name: Download node dependencies
          command: npm install

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
            - v1-dependencies- # fallback if cache not found

      - run:
          name: Clojure classpath
          command: clojure -Spath

      - run:
          name: Run ci tests
          command: ./script/ci-tests.sh

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}

      - save_cache:
          paths:
            - ./node_modules
          key: v1-npm-dependencies-{{ checksum "package-lock.json" }}

      - store_test_results:
          path: target/out/test-results

      - store_artifacts:
          path: target/out/test-results

jobs:
  openjdk11:
    executor:
      name: openjdk
      jdk-version: "11"
    steps: [build]

  openjdk8:
    executor:
      name: openjdk
      jdk-version: "8"
    steps: [build]

workflows:
  test-matrix:
    jobs:
      - openjdk11
      - openjdk8
